#!/bin/sh

function gazee
{
  BASE="$HOME/src/python/gazee"
  cd $BASE

  tmux start-server
  tmux new-session -d -s fob -n vim/gazee
  tmux new-window -t fob:1 -n local/context
  tmux new-window -t fob:2 -n local/scratch

  tmux send-keys -t fob:0 "cd $BASE; vim .devnotes" C-m
  tmux send-keys -t fob:1 "cd $BASE; workon gazee" C-m
  tmux send-keys -t fob:2 "cd $HOME" C-m

  tmux select-window -t fob:0
  tmux attach-session -t fob
}

function social
{
  BASE="$HOME"
  cd $BASE

  tmux new-session -d -s social -n twitter
  tmux new-window -t social:1 -n reddit
  tmux new-window -t social:2 -n hackernews

  tmux send-keys -t social:0 "rainbowstream" C-m
  tmux send-keys -t social:1 "rtv --enable-media" C-m
  tmux send-keys -t social:2 "haxor-news" C-m

  tmux select-window -t social:0
  tmux attach-session -t social
}
